nginx:
    image: 'nginx:1.9'
    volumes:
        - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
        - data
    links:
        - fpm
    environment:
      VIRTUAL_HOST: majisti.skeleton

fpm:
    build: 'docker/fpm'
    volumes_from:
        - data

node:
    build: 'docker/node'
    volumes_from:
        - data

php:
    build: 'docker/php'
    volumes_from:
        - data

ruby:
    build: 'docker/ruby'
    volumes_from:
        - data

data:
    image: busybox
    volumes:
    - .:/var/www/html
    - ~/.composer:/var/www/.composer
