version: '1.0'
steps:
  build-fpm-image:
    type: build
    description: Build the fpm image
    dockerfile: Dockerfile
    image-name: majisti/fpm
    working-directory: ${{initial-clone}}/docker/php/fpm
    tag: 7.1.0.0

  push-fpm-image:
    type: push
    candidate: ${{build-fpm-image}}
    tag: 7.1.0.0

  build-php-image:
    type: build
    description: Build the php image
    dockerfile: Dockerfile
    image-name: majisti/php-cli
    working-directory: ${{initial-clone}}/docker/php/cli
    tag: 7.1.0.0

  push-php-image:
    type: push
    candidate: ${{build-php-image}}
    tag: 7.1.0.0
