nginx:
    build: nginx
    volumes_from:
        - data
    links:
        - fpm
    environment:
      VIRTUAL_HOST: majisti.local

fpm:
    build: php/fpm
    volumes_from:
        - data

node:
    build: node
    volumes_from:
        - data

php:
    build: php/cli
    volumes_from:
        - data

data:
    image: busybox
    volumes:
        - ..:/var/www/html
        - ~/.composer:/home/user/.composer
