nginx:
    build: nginx
    links:
        - fpm
    environment:
      VIRTUAL_HOST: majisti.local
    volumes:
        - ..:/var/www/html

fpm:
    build: php/fpm
    volumes:
        - ..:/var/www/html

node:
    build: node
    volumes:
        - ..:/var/www/html

php:
    build: php/cli
    volumes:
        - ..:/var/www/html
        - ~/.composer:/home/user/.composer
